#ifndef CONTAINER_VERSION_H
#define CONTAINER_VERSION_H

#define CONTAINER_VERSION_MAJOR 0
#define CONTAINER_VERSION_MINOR 1
#define CONTAINER_VERSION_PATCH 0
#define CONTAINER_VERSION_STRING "0.1.0"

#endif /* CONTAINER_VERSION_H */
